### ISSUE TITLE
Post-match screen does not always pop up

### ISSUE THREAD

**Issue by camerongraybill** [Heroes-Profile/HeroesProfile.Uploader#20]
I've noticed that sometimes I do not get a post-match page popping up. I think it is when I queue with other friends on my team who are also using the uploader, and one of them uploads faster?

Not totally sure. Would logs be helpful?

It would be nice if it would log something every time it was opening either the pre-match or post-match page. Would make it easier to figure out if it was a me problem or an uploader problem.

Thanks for the awesome tool/website!

**Comment by Zemill** [comment]
Yes, you are right, I forgot to incorporate it into the path of duplicates.  This won't make it into the next release as I also have to update the Heroes Profile API process to return replayIDs through the duplicate check process, so this will be in the update after the one coming today

**Comment by VashSan** [comment]
I have looked into this and I am testing a slight adaption, which I have a question on: In the current implementation there is a (repeated) request to the postmatch page. The motivation seems to only open if the results are ready.

What actually happens is that the server responds with "TooManyRequests" in my case. If this happens, my impression is that the repeated requests do not help here. In fact the load on the server is always at least doubled as the first successful request is happening and then it is passed to the browser.

So my idea is to just wait some seconds and then directly open the page without any previous request. In case of a 429 response the user still may reload it in the browser. Maybe this is not desired for some other reason, but I would like to see this instead of waiting and nothing happening at all.

Id love to hear your opinion on this before submittin a PR.
